apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8-pv
  labels:
    app:  fastapi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data

