apiVersion: v1
kind: Pod
metadata:
  name: k8-pod-pv-pvc
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - mountPath: "/data"
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: k8-pvc