apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update
spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: rolling-update

  template:
    metadata:
      labels:
        app: rolling-update

    spec:
      containers:
        - name: rolling-update-cont
          image: api-rolling-upd:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          startupProbe:
            httpGet:
              path: /health/startup
              port: 8000
            failureThreshold: 30
            periodSeconds: 5


            