FROM python:3.11-slim as builder
WORKDIR /app
COPY requirements.txt.pvpvc .
RUN pip install --no-cache-dir  \
    --requirement=requirement.txt.pvpvc
#--------#
FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.11 /usr/local/lib/python3.11
COPY --from=builder /usr/local/bin /usr/local/bin
COPY app/ app/
RUN mkdir -p /data
EXPOSE 8000

ENTRYPOINT ["uvicorn"]
CMD ["app.fastapi_mvp:app", "--host", "0.0.0.0", "--port", "8000"]





