FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements.txt.pvpvc .
RUN pip install --no-cache-dir  \
    --prefix=/install \
    --requirement=requirements.txt.pvpvc
#--------#
FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /install /usr/local
COPY app/ app/
RUN mkdir -p /data
EXPOSE 8000

ENTRYPOINT ["uvicorn"]
CMD ["app.fastapi_mvp:app", "--host", "0.0.0.0", "--port", "8000"]





